"""add Department

Revision ID: 897f2d4a98da
Revises: 73e8ddc6735f
Create Date: 2025-06-13 16:11:30.000334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897f2d4a98da'
down_revision = '73e8ddc6735f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
